# Makefile for the ecmd Extensions

EXTENSION_NAME   := cip

# Base info
SUBDIR     := ext/${EXTENSION_NAME}/perlapi/

# This is Additional extension for the client api
SOURCE       :=

# These are additional includes for the client api
INCLUDES     :=

# Include the common extension makefile to do all the work
include ../../template/perlapi/makefile.perlapi

