// fapi2AttributeService.C
// This file is generated by perl script fapi2CreateIfAttrService.pl

#include <fapi2AttributeService.H>
#include <fapi2ChipEcFeature.H>
#include <fapi2PlatTrace.H>

namespace fapi2
{

ReturnCode fapi2GetInitFileAttr(const AttributeId i_id,
                               const Target * i_pTarget,
                               uint64_t & o_val,
                               const uint32_t i_arrayIndex1,
                               const uint32_t i_arrayIndex2,
                               const uint32_t i_arrayIndex3,
                               const uint32_t i_arrayIndex4)
{
    ReturnCode l_rc;

    if (i_id == ATTR_CHIP_ID)
    {
        ATTR_CHIP_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_NAME)
    {
        ATTR_NAME_Type l_attr;
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_NAME, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EC)
    {
        ATTR_EC_Type l_attr;
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_EC, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FSI_GP_REG_SCOM_ACCESS)
    {
        ATTR_FSI_GP_REG_SCOM_ACCESS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FSI_GP_REG_SCOM_ACCESS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FABRIC_NODE_ID)
    {
        ATTR_FABRIC_NODE_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FABRIC_NODE_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FABRIC_CHIP_ID)
    {
        ATTR_FABRIC_CHIP_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FABRIC_CHIP_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_HAS_SBE)
    {
        ATTR_CHIP_HAS_SBE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_HAS_SBE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_DCM_INSTALLED)
    {
        ATTR_PROC_DCM_INSTALLED_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_DCM_INSTALLED, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_REGIONS_TO_ENABLE)
    {
        ATTR_CHIP_REGIONS_TO_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_REGIONS_TO_ENABLE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EX_L2_SINGLE_MEMBER_ENABLE)
    {
        ATTR_EX_L2_SINGLE_MEMBER_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EX_L2_SINGLE_MEMBER_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_BOOT_VOLTAGE_VID)
    {
        ATTR_PROC_BOOT_VOLTAGE_VID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_BOOT_VOLTAGE_VID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PCI_OSCSWITCH_CONFIG)
    {
        ATTR_PCI_OSCSWITCH_CONFIG_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PCI_OSCSWITCH_CONFIG, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_OSCSWITCH_CTL0)
    {
        ATTR_OSCSWITCH_CTL0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_OSCSWITCH_CTL0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_OSCSWITCH_CTL1)
    {
        ATTR_OSCSWITCH_CTL1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_OSCSWITCH_CTL1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_OSCSWITCH_CTL2)
    {
        ATTR_OSCSWITCH_CTL2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_OSCSWITCH_CTL2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_I2C_SLAVE_ADDRESS)
    {
        ATTR_I2C_SLAVE_ADDRESS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_I2C_SLAVE_ADDRESS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_TARGET_SCOMABLE)
    {
        ATTR_TARGET_SCOMABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_TARGET_SCOMABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SIGNED_TEST_8)
    {
        ATTR_SIGNED_TEST_8_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SIGNED_TEST_8, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SIGNED_TEST_32)
    {
        ATTR_SIGNED_TEST_32_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SIGNED_TEST_32, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SIGNED_TEST_64)
    {
        ATTR_SIGNED_TEST_64_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SIGNED_TEST_64, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_1)
    {
        ATTR_SCRATCH_UINT8_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_2)
    {
        ATTR_SCRATCH_UINT8_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_1)
    {
        ATTR_SCRATCH_UINT32_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_2)
    {
        ATTR_SCRATCH_UINT32_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_1)
    {
        ATTR_SCRATCH_UINT64_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_2)
    {
        ATTR_SCRATCH_UINT64_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_ARRAY_1)
    {
        ATTR_SCRATCH_UINT8_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT8_ARRAY_2)
    {
        ATTR_SCRATCH_UINT8_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY_1)
    {
        ATTR_SCRATCH_UINT32_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY_2)
    {
        ATTR_SCRATCH_UINT32_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_SCRATCH_UINT64_ARRAY_1)
    {
        ATTR_SCRATCH_UINT64_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT64_ARRAY_2)
    {
        ATTR_SCRATCH_UINT64_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_SCRATCH_INT8_1)
    {
        ATTR_SCRATCH_INT8_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT8_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT8_2)
    {
        ATTR_SCRATCH_INT8_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT8_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT32_1)
    {
        ATTR_SCRATCH_INT32_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT32_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT32_2)
    {
        ATTR_SCRATCH_INT32_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT32_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT64_1)
    {
        ATTR_SCRATCH_INT64_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT64_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT64_2)
    {
        ATTR_SCRATCH_INT64_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT64_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT8_ARRAY_1)
    {
        ATTR_SCRATCH_INT8_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT8_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_INT8_ARRAY_2)
    {
        ATTR_SCRATCH_INT8_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT8_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_SCRATCH_INT32_ARRAY_1)
    {
        ATTR_SCRATCH_INT32_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT32_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_INT32_ARRAY_2)
    {
        ATTR_SCRATCH_INT32_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT32_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_SCRATCH_INT64_ARRAY_1)
    {
        ATTR_SCRATCH_INT64_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT64_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_INT64_ARRAY_2)
    {
        ATTR_SCRATCH_INT64_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT64_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8)
    {
        ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_CHIP_UNIT_POS)
    {
        ATTR_CHIP_UNIT_POS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_UNIT_POS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FUNCTIONAL)
    {
        ATTR_FUNCTIONAL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FUNCTIONAL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_POS)
    {
        ATTR_POS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_POS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EXECUTION_PLATFORM)
    {
        ATTR_EXECUTION_PLATFORM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EXECUTION_PLATFORM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_IS_SIMULATION)
    {
        ATTR_IS_SIMULATION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_IS_SIMULATION, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MNFG_FLAGS)
    {
        ATTR_MNFG_FLAGS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MNFG_FLAGS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_IS_MPIPL)
    {
        ATTR_IS_MPIPL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_IS_MPIPL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_EPS_TABLE_TYPE)
    {
        ATTR_PROC_EPS_TABLE_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_EPS_TABLE_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FABRIC_PUMP_MODE)
    {
        ATTR_PROC_FABRIC_PUMP_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FABRIC_PUMP_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_X_BUS_WIDTH)
    {
        ATTR_PROC_X_BUS_WIDTH_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_X_BUS_WIDTH, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_ALL_MCS_IN_INTERLEAVING_GROUP)
    {
        ATTR_ALL_MCS_IN_INTERLEAVING_GROUP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_ALL_MCS_IN_INTERLEAVING_GROUP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_NEST_FREQ_MHZ)
    {
        ATTR_NEST_FREQ_MHZ_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_NEST_FREQ_MHZ, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_BOOT_FREQ_MHZ)
    {
        ATTR_BOOT_FREQ_MHZ_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_BOOT_FREQ_MHZ, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EX_GARD_BITS)
    {
        ATTR_EX_GARD_BITS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EX_GARD_BITS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_DISABLE_I2C_ACCESS)
    {
        ATTR_DISABLE_I2C_ACCESS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_DISABLE_I2C_ACCESS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PIB_I2C_REFCLOCK)
    {
        ATTR_PIB_I2C_REFCLOCK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PIB_I2C_REFCLOCK, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PIB_I2C_NEST_PLL)
    {
        ATTR_PIB_I2C_NEST_PLL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PIB_I2C_NEST_PLL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SBE_IMAGE_OFFSET)
    {
        ATTR_SBE_IMAGE_OFFSET_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SBE_IMAGE_OFFSET, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_BOOT_VOLTAGE)
    {
        ATTR_BOOT_VOLTAGE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_BOOT_VOLTAGE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_RISK_LEVEL)
    {
        ATTR_RISK_LEVEL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_RISK_LEVEL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_REFCLOCK_RCVR_TERM)
    {
        ATTR_PROC_REFCLOCK_RCVR_TERM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_REFCLOCK_RCVR_TERM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PCI_REFCLOCK_RCVR_TERM)
    {
        ATTR_PCI_REFCLOCK_RCVR_TERM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PCI_REFCLOCK_RCVR_TERM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MEMB_DMI_REFCLOCK_RCVR_TERM)
    {
        ATTR_MEMB_DMI_REFCLOCK_RCVR_TERM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MEMB_DMI_REFCLOCK_RCVR_TERM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MEMB_DDR_REFCLOCK_RCVR_TERM)
    {
        ATTR_MEMB_DDR_REFCLOCK_RCVR_TERM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MEMB_DDR_REFCLOCK_RCVR_TERM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MEM_FILTER_PLL_SOURCE)
    {
        ATTR_MEM_FILTER_PLL_SOURCE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MEM_FILTER_PLL_SOURCE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MULTI_SCOM_BUFFER_MAX_SIZE)
    {
        ATTR_MULTI_SCOM_BUFFER_MAX_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MULTI_SCOM_BUFFER_MAX_SIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_RECONFIGURE_LOOP)
    {
        ATTR_RECONFIGURE_LOOP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_RECONFIGURE_LOOP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_HWP_ATTR_VERSION)
    {
        ATTR_PM_HWP_ATTR_VERSION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_HWP_ATTR_VERSION, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_REDUNDANT_CLOCKS)
    {
        ATTR_REDUNDANT_CLOCKS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_REDUNDANT_CLOCKS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MFG_TRACE_ENABLE)
    {
        ATTR_MFG_TRACE_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MFG_TRACE_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else
    {
        FAPI_ERR("fapi2GetInitFileAttr: Unrecognized attr ID: 0x%x", i_id);
        l_rc.setFapiError(FAPI_RC_INVALID_ATTR_GET); // FIXME
        l_rc.addEIFfdc(0, &i_id, sizeof(i_id)); // FIXME
    }

    if (l_rc)
    {
        if (i_pTarget)
        {
            FAPI_ERR("fapi2GetInitFileAttr: Error getting attr ID 0x%x from targType 0x%x",
                     i_id, i_pTarget->getType());
        }
        else
        {
            FAPI_ERR("fapi2GetInitFileAttr: Error getting attr ID 0x%x from system target",
                     i_id);
        }
    }

    return l_rc;
}

}
