// fapi2_chip_ec_feature.C
// This file is generated by perl script parseAttributeInfo.pl
// It implements the queryfapi2_chip_ec_feature function

#include <fapi2_chip_ec_feature.H>
#include <fapi2_attribute_service.H>
#include <systemConfig.H>
#include <plat_trace.H>

namespace fapi2
{

template< TargetType K >
ReturnCode queryChipEcFeature(AttributeId i_id,
                    const Target<K>& i_pTarget,
                    uint8_t & o_hasFeature)
{
    o_hasFeature = false;
    ReturnCode l_rc;
    uint8_t l_chipName = 0;
    uint8_t l_chipEc = 0;

    if (i_pTarget.isChiplet())
    {
        Target<TARGET_TYPE_ALL> l_target = i_pTarget.getParent();
    }

    if (!l_rc)
    {
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_NAME, &l_target, l_chipName);

        if (l_rc)
        {
            FAPI_ERR("queryChipEcFeature: error getting chip name");
        }
        else
        {
            l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_EC, &l_target, l_chipEc);

            if (l_rc)
            {
                FAPI_ERR("queryChipEcFeature: error getting chip ec");
            }
            else
            {
                switch (i_id)
                {
                default:
                    FAPI_ERR("queryChipEcFeature: Unknown feature 0x%x",
                        i_id);
                    l_rc.setFapiError(FAPI_RC_INVALID_CHIP_EC_FEATURE_GET);
                    l_rc.addEIFfdc(0, &i_id, sizeof(i_id));
                    break;
                }

                if (o_hasFeature)
                {
                    FAPI_INF("queryChipEcFeature: Chip (0x%x:0x%x) has feature (0x%x)", l_chipName, l_chipEc, i_id);
                }
                else
                {
                    FAPI_INF("queryChipEcFeature: Chip (0x%x:0x%x) does not have feature (0x%x)", l_chipName, l_chipEc, i_id);
                }
            }
        }
    }
    return l_rc;
}

}
