// fapi2ChipEcFeature.C
// This file is generated by perl script fapi2ParseAttributeInfo.pl
// It implements the fapi2QueryChipEcFeature function

#include <fapi2ChipEcFeature.H>
#include <fapi2AttributeService.H>
#include <fapi2SystemConfig.H>
#include <fapi2PlatTrace.H>

namespace fapi2
{

fapi2::ReturnCode fapi2QueryChipEcFeature(fapi2::AttributeId i_id,
                                        const fapi2::Target * i_pTarget, // FIXME
                                        uint8_t & o_hasFeature)
{
    o_hasFeature = false;
    fapi2::ReturnCode l_rc(FAPI2_RC_SUCCESS);
    uint8_t l_chipName = 0;
    uint8_t l_chipEc = 0;
    fapi2::Target l_target = *i_pTarget; // FIXME

    if (i_pTarget->isChiplet())
    {
        l_rc = fapi2GetParentChip(*i_pTarget, l_target);

        if (l_rc)
        {
            FAPI_ERR("fapi2QueryChipEcFeature: error getting parent chip");
        }
    }

    if (!l_rc)
    {
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_NAME, &l_target, l_chipName);

        if (l_rc)
        {
            FAPI_ERR("fapi2QueryChipEcFeature: error getting chip name");
        }
        else
        {
            l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_EC, &l_target, l_chipEc);

            if (l_rc)
            {
                FAPI_ERR("fapi2QueryChipEcFeature: error getting chip ec");
            }
            else
            {
                switch (i_id)
                {
                default:
                    FAPI_ERR("fapi2QueryChipEcFeature: Unknown feature 0x%x",
                        i_id);
                    l_rc.setFapiError(FAPI_RC_INVALID_CHIP_EC_FEATURE_GET);
                    l_rc.addEIFfdc(0, &i_id, sizeof(i_id));
                    break;
                }

                if (o_hasFeature)
                {
                    FAPI_INF("fapi2QueryChipEcFeature: Chip (0x%x:0x%x) has feature (0x%x)", l_chipName, l_chipEc, i_id);
                }
                else
                {
                    FAPI_INF("fapi2QueryChipEcFeature: Chip (0x%x:0x%x) does not have feature (0x%x)", l_chipName, l_chipEc, i_id);
                }
            }
        }
    }
    return l_rc;
}

}
