# Makefile for the ecmd Extensions
# Written by Chris Engel

# $Header$

ECMD_ROOT       := ${PWD}/../../../
# The default build rules
include ${ECMD_ROOT}/makefile.rules

EXTENSION_NAME   := cip


# Additional Source files for the Client API
CAPI_SOURCE  :=

# Additional Source files for the Shared Lib
SLIB_SOURCE  :=

# These are additional includes for the client api
INCLUDES     :=


# Include the common extension makefile to do all the work
include ../../template/capi/makefile.capi

