# $Header$
# Makefile for the ecmd Extensions

EXTENSION_NAME   := fapi2

# Base info and default build rules
SUBDIR     := ext/${EXTENSION_NAME}/perlapi/
include ../../../makefile.rules

# This is Additional extension for the client api
SOURCE       :=

# These are additional includes for the client api
INCLUDES     :=

# Include the common extension makefile to do all the work
include ../../template/perlapi/makefile.perlapi

