# Makefile for the ecmd Extensions

# *****************************************************************************
# Include the common base makefile
# *****************************************************************************
include ../../../../makefile.base

EXTENSION_NAME := cip

# Additional Source files for the Client API
CAPI_SOURCE  :=

# Additional Source files for the Shared Lib
SLIB_SOURCE  :=

# These are additional includes for the client api
INCLUDES     :=

# Include the common extension makefile to do all the work
include ${EXT_TEMPLATE_PATH}/capi/makefile.capi
