# Makefile for the ecmd Extensions

EXTENSION_NAME   := cip

# Base info
SUBDIR     := ext/${EXTENSION_NAME}/capi/

# Additional Source files for the Client API
CAPI_SOURCE  :=

# Additional Source files for the Shared Lib
SLIB_SOURCE  :=

# These are additional includes for the client api
INCLUDES     :=

# Include the common extension makefile to do all the work
include ../../template/capi/makefile.capi

