# Makefile for the ecmd Extensions

# *****************************************************************************
# Include any global variables
# *****************************************************************************
include ../../../../makefile.vars

EXTENSION_NAME   := cip

# This is Additional extension for the client api
SOURCE       := cipProcUser.C cipPoreUser.C

# These are additional includes for the client api
INCLUDES     :=

# Include the common extension makefile to do all the work
include ${EXT_TEMPLATE_PATH}/cmd/makefile.cmd

