# Makefile for the ecmd Extensions

# This make file does nothing since there is no cmd command line
# programs to build
# If this ever changes, grab a make for for another extension and
# follow that template

all: ;

clean: ;
