# Makefile for the ecmd Extensions
# Written by Chris Engel

# $Header$



EXTENSION_NAME   := cip


# This is Additional extension for the client api
SOURCE       := cipProcUser.C

# These are additional includes for the client api
INCLUDES     :=


# Include the common extension makefile to do all the work
include ../../template/cmd/makefile.cmd

