// fapiAttributeService.C
// This file is generated by perl script fapiParseAttributeInfo.pl

#include <fapiAttributeService.H>

namespace fapi
{

ReturnCode fapiGetInitFileAttr(const AttributeId i_id,
                               const Target * i_pTarget,
                               uint64_t & o_val,
                               const uint32_t i_arrayIndex1,
                               const uint32_t i_arrayIndex2,
                               const uint32_t i_arrayIndex3,
                               const uint32_t i_arrayIndex4)
{
    ReturnCode l_rc;

    if (i_id == ATTR_SCRATCH_UINT8_1)
    {
        ATTR_SCRATCH_UINT8_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_2)
    {
        ATTR_SCRATCH_UINT8_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_1)
    {
        ATTR_SCRATCH_UINT32_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_2)
    {
        ATTR_SCRATCH_UINT32_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_1)
    {
        ATTR_SCRATCH_UINT64_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_2)
    {
        ATTR_SCRATCH_UINT64_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_ARRAY_1)
    {
        ATTR_SCRATCH_UINT8_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT8_ARRAY_2)
    {
        ATTR_SCRATCH_UINT8_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY_1)
    {
        ATTR_SCRATCH_UINT32_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY_2)
    {
        ATTR_SCRATCH_UINT32_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_SCRATCH_UINT64_ARRAY_1)
    {
        ATTR_SCRATCH_UINT64_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT64_ARRAY_2)
    {
        ATTR_SCRATCH_UINT64_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8)
    {
        ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_NUM_RANKS_PER_DIMM)
    {
        ATTR_EFF_NUM_RANKS_PER_DIMM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_NUM_RANKS_PER_DIMM, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_TYPE)
    {
        ATTR_EFF_DIMM_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_TYPE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_GEN)
    {
        ATTR_EFF_DRAM_GEN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_GEN, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_ODT_RD)
    {
        ATTR_EFF_ODT_RD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_ODT_RD, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_ODT_WR)
    {
        ATTR_EFF_ODT_WR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_ODT_WR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DRAM_RON)
    {
        ATTR_EFF_DRAM_RON_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RON, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_RTT_NOM)
    {
        ATTR_EFF_DRAM_RTT_NOM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RTT_NOM, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DRAM_RTT_WR)
    {
        ATTR_EFF_DRAM_RTT_WR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RTT_WR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DRAM_WR_VREF)
    {
        ATTR_EFF_DRAM_WR_VREF_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR_VREF, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_DQ_DQS)
    {
        ATTR_EFF_CEN_DRV_IMP_DQ_DQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_DQ_DQS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_CMD)
    {
        ATTR_EFF_CEN_DRV_IMP_CMD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_CMD, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_CNTL)
    {
        ATTR_EFF_CEN_DRV_IMP_CNTL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_CNTL, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_CEN_RCV_IMP_DQ_DQS)
    {
        ATTR_EFF_CEN_RCV_IMP_DQ_DQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RCV_IMP_DQ_DQS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_DQ)
    {
        ATTR_EFF_CEN_SLEW_RATE_DQ_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_DQ, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_DQS)
    {
        ATTR_EFF_CEN_SLEW_RATE_DQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_DQS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_CMD)
    {
        ATTR_EFF_CEN_SLEW_RATE_CMD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_CMD, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_CNTL)
    {
        ATTR_EFF_CEN_SLEW_RATE_CNTL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_CNTL, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_CEN_RD_VREF)
    {
        ATTR_EFF_CEN_RD_VREF_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RD_VREF, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_SIZE)
    {
        ATTR_EFF_DIMM_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_SIZE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_DENSITY)
    {
        ATTR_EFF_DRAM_DENSITY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DENSITY, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_BL)
    {
        ATTR_EFF_DRAM_BL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_BL, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_CL)
    {
        ATTR_EFF_DRAM_CL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_CL, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_AL)
    {
        ATTR_EFF_DRAM_AL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_AL, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_CWL)
    {
        ATTR_EFF_DRAM_CWL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_CWL, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_RBT)
    {
        ATTR_EFF_DRAM_RBT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RBT, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_TM)
    {
        ATTR_EFF_DRAM_TM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TM, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_DLL_RESET)
    {
        ATTR_EFF_DRAM_DLL_RESET_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DLL_RESET, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_WR)
    {
        ATTR_EFF_DRAM_WR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_DLL_PPD)
    {
        ATTR_EFF_DRAM_DLL_PPD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DLL_PPD, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_DLL_ENABLE)
    {
        ATTR_EFF_DRAM_DLL_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DLL_ENABLE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_TDQS)
    {
        ATTR_EFF_DRAM_TDQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TDQS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_WR_LVL_ENABLE)
    {
        ATTR_EFF_DRAM_WR_LVL_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR_LVL_ENABLE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_OUTPUT_BUFFER)
    {
        ATTR_EFF_DRAM_OUTPUT_BUFFER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_OUTPUT_BUFFER, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_PASR)
    {
        ATTR_EFF_DRAM_PASR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_PASR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_ASR)
    {
        ATTR_EFF_DRAM_ASR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_ASR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_SRT)
    {
        ATTR_EFF_DRAM_SRT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_SRT, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_MPR_LOC)
    {
        ATTR_EFF_MPR_LOC_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_MPR_LOC, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_MPR_MODE)
    {
        ATTR_EFF_MPR_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_MPR_MODE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15)
    {
        ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_IS_SIMULATION)
    {
        ATTR_IS_SIMULATION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_IS_SIMULATION, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_EFF_PRIMARY_RANK)
    {
        ATTR_MSS_EFF_PRIMARY_RANK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_EFF_PRIMARY_RANK, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else
    {
        FAPI_ERR("fapiGetInitFileAttr: Unrecognized attr: %d", i_id);
        ReturnCodeFfdc::addEIFfdc(l_rc, static_cast<uint32_t>(i_id));        l_rc = FAPI_RC_INVALID_ATTR_GET;
    }

    if (l_rc)
    {
        FAPI_ERR("fapiGetInitFileAttr: Error getting attr");
    }

    return l_rc;
}

}
