// fapiChipEcFeature.C
// This file is generated by perl script fapiParseAttributeInfo.pl
// It implements the fapiQueryChipEcFeature function

#include <fapiChipEcFeature.H>
#include <fapiAttributeService.H>
#include <fapiSystemConfig.H>
#include <fapiPlatTrace.H>

namespace fapi
{

fapi::ReturnCode fapiQueryChipEcFeature(fapi::AttributeId i_id,
                                        const fapi::Target * i_pTarget,
                                        uint8_t & o_hasFeature)
{
    o_hasFeature = false;
    fapi::ReturnCode l_rc;
    uint8_t l_chipName = 0;
    uint8_t l_chipEc = 0;
    fapi::Target l_target = *i_pTarget;

    if (i_pTarget->isChiplet())
    {
        l_rc = fapiGetParentChip(*i_pTarget, l_target);

        if (l_rc)
        {
            FAPI_ERR("fapiQueryChipEcFeature: error getting parent chip");
        }
    }

    if (!l_rc)
    {
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_NAME, &l_target, l_chipName);

        if (l_rc)
        {
            FAPI_ERR("fapiQueryChipEcFeature: error getting chip name");
        }
        else
        {
            l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_EC, &l_target, l_chipEc);

            if (l_rc)
            {
                FAPI_ERR("fapiQueryChipEcFeature: error getting chip ec");
            }
            else
            {
                switch (i_id)
                {
                case ATTR_CHIP_EC_FEATURE_TEST1:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc == 0x10))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc > 0x30))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_TEST2:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_ENABLE_PAGE_MODE_FOR_RRQ:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_ENABLE_TRACE_LCL_CLK_GATE_CTRL:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_ENABLE_NM_CHANGE_AFTER_SYNC:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_ENABLE_ROW_HAMMER_FEATURE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_WRITE_FIR_MASK_FEATURE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc == 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_MSS_CONTINUE_ON_DP18_PLL_LOCK_FAIL:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc == 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_MSS_READ_PHASE_SELECT_RESET:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc == 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_CHECK_L4_CACHE_ENABLE_UNKNOWN:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_MSS_DISABLE1_REG_FIXED:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_ECID_CONTAINS_PORT_LOGIC_BAD_INDICATION:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_MCBIST_RANDOM_DATA_GEN:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_MCBIST_TRAP_RESET:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_MCBIST_RANDOM_ADDRESS:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_SCOM_PARITY_ERROR_HW244827_FIXED:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_HW217608_MBSPA_0_CMD_COMPLETE_ATTN_FIXED:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_USE_FIRST_SUPPLIER_FOR_INVALID_MODULE_ID:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_ENABLE_SAFEMODE_THROTTLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CENTAUR_EC_DD2_FIR_BIT_DEFN_CHANGES:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_VENICE_SPECIFIC:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_HW_BUG_PIBSLVRESET:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_BOOT_FREQ_LESS_PSAVE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc == 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_HW_BUG_PLLINIT:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_SECURE_IOVALID_PRESENT:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_NOT_SUPPORT_SBE_CFAM_START:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_NOT_SUPPORT_SBE_AUTO_START:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_32_PCIE_LANES:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_CAPP_HANG_CONTROL_ON_SCOM:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_CAPP_PROD:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_NX_HANG_CONTROL_ON_SCOM:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_HCA_SPLIT_HANG_CONTROL:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_RECAL_DFE_ENABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_RECAL_DDC_ENABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_RECAL_CTLE_ENABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_LCTANK_PLL_VCO_BUG:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_XBUS_DLL_SLOW_MURANO:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x12))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_ADU_PBINIT_LAUNCH_BUG:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_MCS_ECC_BYPASS_DISABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_TRACE_CONTROL_ON_SCOM:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_MPIPL_AISS_WINKLE_ENTRY:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_FBC_SERIAL_SCOM_WE5_VER2:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_FBC_SERIAL_SCOM_C8_VER3:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_FBC_SERIAL_SCOM_C8_VER2:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc == 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_FBC_UX_SCOPE_ARB_RR:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_FBC_SERIAL_SCOM_C10_VER2:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_MCD_HANG_RECOVERY_BUG:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_PCBS_ERR_RESET:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_IO_TRAINING_SLS_WORKAROUND:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc <= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_IO_TRAINING_DLL_WORKAROUND:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc <= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_DCCAL_PLL_WORKAROUND:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc <= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_RESONANT_CLK_VALID:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_AISS_SPECIAL_WAKEUP:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_CFAM_RESET_SBE_START_WA:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_OCC_CE_FIR_DISABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_ENABLE_IVE_PERFORMANCE_ORDERING:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_ENABLE_PCI_DMAR_OOO:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_ZCAL_OVERRIDE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_IVRM_WINKLE_BUG:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc > 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_PROC_EC_MSS_RECONFIG_POSSIBLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CEN_EC_THROTTLE_SYNC_POSSIBLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_CENTAUR) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_PROC_EC_CORE_HANG_PULSE_BUG:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_PROC_EC_PBA_PREFETCH_ENABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x21))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_PROC_EC_OHA_L3_PURGE_ABORT_ENABLE:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x20))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_DPLL_FMIN_FMAX_BUG_WA:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc < 0x13))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_FINE_DELAY_INVERT_WA:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_MURANO) &&
                         (l_chipEc >= 0x20))
                    ||
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc >= 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                case ATTR_CHIP_EC_FEATURE_CPM4_NO_CAL_WA:
                    if (
                        ((l_chipName == ENUM_ATTR_NAME_VENICE) &&
                         (l_chipEc == 0x10))
                       )
                    {
                        o_hasFeature = true;
                    }
                    break;
                default:
                    FAPI_ERR("fapiQueryChipEcFeature: Unknown feature 0x%x",
                        i_id);
                    l_rc.setFapiError(FAPI_RC_INVALID_CHIP_EC_FEATURE_GET);
                    l_rc.addEIFfdc(0, &i_id, sizeof(i_id));
                    break;
                }

                if (o_hasFeature)
                {
                    FAPI_INF("fapiQueryChipEcFeature: Chip (0x%x:0x%x) has feature (0x%x)", l_chipName, l_chipEc, i_id);
                }
                else
                {
                    FAPI_INF("fapiQueryChipEcFeature: Chip (0x%x:0x%x) does not have feature (0x%x)", l_chipName, l_chipEc, i_id);
                }
            }
        }
    }
    return l_rc;
}

}
