// fapiAttributeService.C
// This file is generated by perl script fapiCreateIfAttrService.pl

#include <fapiAttributeService.H>
#include <fapiChipEcFeature.H>
#include <fapiPlatTrace.H>

namespace fapi
{

ReturnCode fapiGetInitFileAttr(const AttributeId i_id,
                               const Target * i_pTarget,
                               uint64_t & o_val,
                               const uint32_t i_arrayIndex1,
                               const uint32_t i_arrayIndex2,
                               const uint32_t i_arrayIndex3,
                               const uint32_t i_arrayIndex4)
{
    ReturnCode l_rc;

    if (i_id == ATTR_L2_R_T0_EPS)
    {
        ATTR_L2_R_T0_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_R_T0_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_R_T1_EPS)
    {
        ATTR_L2_R_T1_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_R_T1_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_R_T2_EPS)
    {
        ATTR_L2_R_T2_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_R_T2_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_FORCE_R_T2_EPS)
    {
        ATTR_L2_FORCE_R_T2_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_FORCE_R_T2_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_W_EPS)
    {
        ATTR_L2_W_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_W_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_R_T0_EPS)
    {
        ATTR_L3_R_T0_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_R_T0_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_R_T1_EPS)
    {
        ATTR_L3_R_T1_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_R_T1_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_R_T2_EPS)
    {
        ATTR_L3_R_T2_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_R_T2_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_FORCE_R_T2_EPS)
    {
        ATTR_L3_FORCE_R_T2_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_FORCE_R_T2_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_W_EPS)
    {
        ATTR_L3_W_EPS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_W_EPS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_POS)
    {
        ATTR_POS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_POS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_ID)
    {
        ATTR_CHIP_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_NAME)
    {
        ATTR_NAME_Type l_attr;
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_NAME, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EC)
    {
        ATTR_EC_Type l_attr;
        l_rc = FAPI_ATTR_GET_PRIVILEGED(ATTR_EC, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FSI_GP_REG_SCOM_ACCESS)
    {
        ATTR_FSI_GP_REG_SCOM_ACCESS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FSI_GP_REG_SCOM_ACCESS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FABRIC_NODE_ID)
    {
        ATTR_FABRIC_NODE_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FABRIC_NODE_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FABRIC_CHIP_ID)
    {
        ATTR_FABRIC_CHIP_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FABRIC_CHIP_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_HAS_SBE)
    {
        ATTR_CHIP_HAS_SBE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_HAS_SBE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_DCM_INSTALLED)
    {
        ATTR_PROC_DCM_INSTALLED_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_DCM_INSTALLED, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_EC_FEATURE_TEST1)
    {
        ATTR_CHIP_EC_FEATURE_TEST1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_EC_FEATURE_TEST1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_EC_FEATURE_TEST2)
    {
        ATTR_CHIP_EC_FEATURE_TEST2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_EC_FEATURE_TEST2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CEN_DQ_TO_DIMM_CONN_DQ)
    {
        ATTR_CEN_DQ_TO_DIMM_CONN_DQ_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CEN_DQ_TO_DIMM_CONN_DQ, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MBA_PORT)
    {
        ATTR_MBA_PORT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MBA_PORT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MBA_DIMM)
    {
        ATTR_MBA_DIMM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MBA_DIMM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_PROC_REFCLOCK)
    {
        ATTR_FREQ_PROC_REFCLOCK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_PROC_REFCLOCK, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_MEM_REFCLOCK)
    {
        ATTR_FREQ_MEM_REFCLOCK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_MEM_REFCLOCK, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_CORE_FLOOR)
    {
        ATTR_FREQ_CORE_FLOOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_CORE_FLOOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_PB)
    {
        ATTR_FREQ_PB_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_PB, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_A)
    {
        ATTR_FREQ_A_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_A, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_X)
    {
        ATTR_FREQ_X_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_X, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_PCIE)
    {
        ATTR_FREQ_PCIE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_PCIE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MVPD_IVRM_CALIBRATION)
    {
        ATTR_MVPD_IVRM_CALIBRATION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MVPD_IVRM_CALIBRATION, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MVPD_CPM_CALIBRATION)
    {
        ATTR_MVPD_CPM_CALIBRATION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MVPD_CPM_CALIBRATION, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PM_POWER_PROXY_TRACE_TIMER)
    {
        ATTR_PM_POWER_PROXY_TRACE_TIMER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_POWER_PROXY_TRACE_TIMER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PPT_TIMER_MATCH_VALUE)
    {
        ATTR_PM_PPT_TIMER_MATCH_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PPT_TIMER_MATCH_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PPT_TIMER_TICK)
    {
        ATTR_PM_PPT_TIMER_TICK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PPT_TIMER_TICK, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_AISS_TIMEOUT)
    {
        ATTR_PM_AISS_TIMEOUT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_AISS_TIMEOUT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PSTATE_STEPSIZE)
    {
        ATTR_PM_PSTATE_STEPSIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PSTATE_STEPSIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_EXTERNAL_VRM_STEPDELAY_RANGE)
    {
        ATTR_PM_EXTERNAL_VRM_STEPDELAY_RANGE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_EXTERNAL_VRM_STEPDELAY_RANGE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_EXTERNAL_VRM_STEPDELAY_VALUE)
    {
        ATTR_PM_EXTERNAL_VRM_STEPDELAY_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_EXTERNAL_VRM_STEPDELAY_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PMC_HANGPULSE_DIVIDER)
    {
        ATTR_PM_PMC_HANGPULSE_DIVIDER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PMC_HANGPULSE_DIVIDER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PVSAFE_PSTATE)
    {
        ATTR_PM_PVSAFE_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PVSAFE_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_FRAME_SIZE)
    {
        ATTR_PM_SPIVID_FRAME_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_FRAME_SIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_IN_DELAY_FRAME1)
    {
        ATTR_PM_SPIVID_IN_DELAY_FRAME1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_IN_DELAY_FRAME1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_IN_DELAY_FRAME2)
    {
        ATTR_PM_SPIVID_IN_DELAY_FRAME2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_IN_DELAY_FRAME2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_CLOCK_POLARITY)
    {
        ATTR_PM_SPIVID_CLOCK_POLARITY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_CLOCK_POLARITY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_CLOCK_PHASE)
    {
        ATTR_PM_SPIVID_CLOCK_PHASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_CLOCK_PHASE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_CLOCK_DIVIDER)
    {
        ATTR_PM_SPIVID_CLOCK_DIVIDER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_CLOCK_DIVIDER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS)
    {
        ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS_VALUE)
    {
        ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_INTER_RETRY_DELAY_VALUE)
    {
        ATTR_PM_SPIVID_INTER_RETRY_DELAY_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_INTER_RETRY_DELAY_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_INTER_RETRY_DELAY)
    {
        ATTR_PM_SPIVID_INTER_RETRY_DELAY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_INTER_RETRY_DELAY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_CRC_GEN_ENABLE)
    {
        ATTR_PM_SPIVID_CRC_GEN_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_CRC_GEN_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_CRC_CHECK_ENABLE)
    {
        ATTR_PM_SPIVID_CRC_CHECK_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_CRC_CHECK_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_MAJORITY_VOTE_ENABLE)
    {
        ATTR_PM_SPIVID_MAJORITY_VOTE_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_MAJORITY_VOTE_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_MAX_RETRIES)
    {
        ATTR_PM_SPIVID_MAX_RETRIES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_MAX_RETRIES, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_CRC_POLYNOMIAL_ENABLES)
    {
        ATTR_PM_SPIVID_CRC_POLYNOMIAL_ENABLES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_CRC_POLYNOMIAL_ENABLES, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_OCC_HEARTBEAT_TIME)
    {
        ATTR_PM_OCC_HEARTBEAT_TIME_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_OCC_HEARTBEAT_TIME, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SLEEP_WINKLE_REQUEST_TIMEOUT)
    {
        ATTR_PM_SLEEP_WINKLE_REQUEST_TIMEOUT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SLEEP_WINKLE_REQUEST_TIMEOUT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SLEEP_ENTRY)
    {
        ATTR_PM_SLEEP_ENTRY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SLEEP_ENTRY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SLEEP_EXIT)
    {
        ATTR_PM_SLEEP_EXIT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SLEEP_EXIT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SLEEP_TYPE)
    {
        ATTR_PM_SLEEP_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SLEEP_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_WINKLE_TYPE)
    {
        ATTR_PM_WINKLE_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_WINKLE_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_CORE_DELAY0)
    {
        ATTR_PM_PFET_POWERUP_CORE_DELAY0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_CORE_DELAY0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_CORE_DELAY1)
    {
        ATTR_PM_PFET_POWERUP_CORE_DELAY1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_CORE_DELAY1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_CORE_DELAY0_VALUE)
    {
        ATTR_PM_PFET_POWERUP_CORE_DELAY0_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_CORE_DELAY0_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_CORE_DELAY1_VALUE)
    {
        ATTR_PM_PFET_POWERUP_CORE_DELAY1_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_CORE_DELAY1_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_CORE_SEQUENCE_DELAY_SELECT)
    {
        ATTR_PM_PFET_POWERUP_CORE_SEQUENCE_DELAY_SELECT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_CORE_SEQUENCE_DELAY_SELECT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_CORE_DELAY0)
    {
        ATTR_PM_PFET_POWERDOWN_CORE_DELAY0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_CORE_DELAY0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_CORE_DELAY1)
    {
        ATTR_PM_PFET_POWERDOWN_CORE_DELAY1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_CORE_DELAY1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_CORE_DELAY0_VALUE)
    {
        ATTR_PM_PFET_POWERDOWN_CORE_DELAY0_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_CORE_DELAY0_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_CORE_DELAY1_VALUE)
    {
        ATTR_PM_PFET_POWERDOWN_CORE_DELAY1_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_CORE_DELAY1_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_CORE_SEQUENCE_DELAY_SELECT)
    {
        ATTR_PM_PFET_POWERDOWN_CORE_SEQUENCE_DELAY_SELECT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_CORE_SEQUENCE_DELAY_SELECT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_ECO_DELAY0)
    {
        ATTR_PM_PFET_POWERUP_ECO_DELAY0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_ECO_DELAY0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_ECO_DELAY1)
    {
        ATTR_PM_PFET_POWERUP_ECO_DELAY1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_ECO_DELAY1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_ECO_DELAY0_VALUE)
    {
        ATTR_PM_PFET_POWERUP_ECO_DELAY0_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_ECO_DELAY0_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_ECO_DELAY1_VALUE)
    {
        ATTR_PM_PFET_POWERUP_ECO_DELAY1_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_ECO_DELAY1_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERUP_ECO_SEQUENCE_DELAY_SELECT)
    {
        ATTR_PM_PFET_POWERUP_ECO_SEQUENCE_DELAY_SELECT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERUP_ECO_SEQUENCE_DELAY_SELECT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_ECO_DELAY0)
    {
        ATTR_PM_PFET_POWERDOWN_ECO_DELAY0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_ECO_DELAY0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_ECO_DELAY1)
    {
        ATTR_PM_PFET_POWERDOWN_ECO_DELAY1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_ECO_DELAY1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_ECO_DELAY0_VALUE)
    {
        ATTR_PM_PFET_POWERDOWN_ECO_DELAY0_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_ECO_DELAY0_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_ECO_DELAY1_VALUE)
    {
        ATTR_PM_PFET_POWERDOWN_ECO_DELAY1_VALUE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_ECO_DELAY1_VALUE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PFET_POWERDOWN_ECO_SEQUENCE_DELAY_SELECT)
    {
        ATTR_PM_PFET_POWERDOWN_ECO_SEQUENCE_DELAY_SELECT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PFET_POWERDOWN_ECO_SEQUENCE_DELAY_SELECT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PSTATE0_FREQUENCY)
    {
        ATTR_PM_PSTATE0_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PSTATE0_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_IVRMS_ENABLED)
    {
        ATTR_PM_IVRMS_ENABLED_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_IVRMS_ENABLED, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SAFE_PSTATE)
    {
        ATTR_PM_SAFE_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SAFE_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_ENABLE)
    {
        ATTR_PM_RESONANT_CLOCK_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_FULL_CSB_PSTATE)
    {
        ATTR_PM_RESONANT_CLOCK_FULL_CSB_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_FULL_CSB_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_LFRLOW_PSTATE)
    {
        ATTR_PM_RESONANT_CLOCK_LFRLOW_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_LFRLOW_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_LFRUPPER_PSTATE)
    {
        ATTR_PM_RESONANT_CLOCK_LFRUPPER_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_LFRUPPER_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_HFRLOW_PSTATE)
    {
        ATTR_PM_RESONANT_CLOCK_HFRLOW_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_HFRLOW_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_HFRHIGH_PSTATE)
    {
        ATTR_PM_RESONANT_CLOCK_HFRHIGH_PSTATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_HFRHIGH_PSTATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_FRAME_SIZE)
    {
        ATTR_PM_SPIPSS_FRAME_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_FRAME_SIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_OUT_COUNT)
    {
        ATTR_PM_SPIPSS_OUT_COUNT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_OUT_COUNT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_IN_DELAY)
    {
        ATTR_PM_SPIPSS_IN_DELAY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_IN_DELAY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_IN_COUNT)
    {
        ATTR_PM_SPIPSS_IN_COUNT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_IN_COUNT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_CLOCK_POLARITY)
    {
        ATTR_PM_SPIPSS_CLOCK_POLARITY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_CLOCK_POLARITY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_CLOCK_PHASE)
    {
        ATTR_PM_SPIPSS_CLOCK_PHASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_CLOCK_PHASE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_CLOCK_DIVIDER)
    {
        ATTR_PM_SPIPSS_CLOCK_DIVIDER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_CLOCK_DIVIDER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_INTER_FRAME_DELAY_SETTING)
    {
        ATTR_PM_SPIPSS_INTER_FRAME_DELAY_SETTING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_INTER_FRAME_DELAY_SETTING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_INTER_FRAME_DELAY)
    {
        ATTR_PM_SPIPSS_INTER_FRAME_DELAY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_INTER_FRAME_DELAY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_RCV_RESERV_TIMEOUT)
    {
        ATTR_PM_PBAX_RCV_RESERV_TIMEOUT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_RCV_RESERV_TIMEOUT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_SND_RETRY_COUNT_OVERCOMMIT_ENABLE)
    {
        ATTR_PM_PBAX_SND_RETRY_COUNT_OVERCOMMIT_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_SND_RETRY_COUNT_OVERCOMMIT_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_SND_RETRY_THRESHOLD)
    {
        ATTR_PM_PBAX_SND_RETRY_THRESHOLD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_SND_RETRY_THRESHOLD, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_SND_RESERV_TIMEOUT)
    {
        ATTR_PM_PBAX_SND_RESERV_TIMEOUT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_SND_RESERV_TIMEOUT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPWUP_FSP)
    {
        ATTR_PM_SPWUP_FSP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPWUP_FSP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPWUP_OCC)
    {
        ATTR_PM_SPWUP_OCC_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPWUP_OCC, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPWUP_PHYP)
    {
        ATTR_PM_SPWUP_PHYP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPWUP_PHYP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_EXTERNAL_VRM_STEPSIZE)
    {
        ATTR_PM_EXTERNAL_VRM_STEPSIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_EXTERNAL_VRM_STEPSIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_EXTERNAL_VRM_STEPDELAY)
    {
        ATTR_PM_EXTERNAL_VRM_STEPDELAY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_EXTERNAL_VRM_STEPDELAY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PSTATE_UNDERVOLTING_MINIMUM)
    {
        ATTR_PM_PSTATE_UNDERVOLTING_MINIMUM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PSTATE_UNDERVOLTING_MINIMUM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PSTATE_UNDERVOLTING_MAXIMUM)
    {
        ATTR_PM_PSTATE_UNDERVOLTING_MAXIMUM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PSTATE_UNDERVOLTING_MAXIMUM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_FREQUENCY)
    {
        ATTR_PM_SPIVID_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIVID_PORT_ENABLE)
    {
        ATTR_PM_SPIVID_PORT_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIVID_PORT_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SAFE_FREQUENCY)
    {
        ATTR_PM_SAFE_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SAFE_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_FULL_CLOCK_SECTOR_BUFFER_FREQUENCY)
    {
        ATTR_PM_RESONANT_CLOCK_FULL_CLOCK_SECTOR_BUFFER_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_FULL_CLOCK_SECTOR_BUFFER_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_LOW_BAND_LOWER_FREQUENCY)
    {
        ATTR_PM_RESONANT_CLOCK_LOW_BAND_LOWER_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_LOW_BAND_LOWER_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_LOW_BAND_UPPER_FREQUENCY)
    {
        ATTR_PM_RESONANT_CLOCK_LOW_BAND_UPPER_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_LOW_BAND_UPPER_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_HIGH_BAND_LOWER_FREQUENCY)
    {
        ATTR_PM_RESONANT_CLOCK_HIGH_BAND_LOWER_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_HIGH_BAND_LOWER_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_RESONANT_CLOCK_HIGH_BAND_UPPER_FREQUENCY)
    {
        ATTR_PM_RESONANT_CLOCK_HIGH_BAND_UPPER_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_RESONANT_CLOCK_HIGH_BAND_UPPER_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_SPIPSS_FREQUENCY)
    {
        ATTR_PM_SPIPSS_FREQUENCY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_SPIPSS_FREQUENCY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_APSS_CHIP_SELECT)
    {
        ATTR_PM_APSS_CHIP_SELECT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_APSS_CHIP_SELECT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_NODEID)
    {
        ATTR_PM_PBAX_NODEID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_NODEID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_CHIPID)
    {
        ATTR_PM_PBAX_CHIPID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_CHIPID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PM_PBAX_BRDCST_ID_VECTOR)
    {
        ATTR_PM_PBAX_BRDCST_ID_VECTOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PM_PBAX_BRDCST_ID_VECTOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_R_LOADLINE)
    {
        ATTR_PROC_R_LOADLINE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_R_LOADLINE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_R_DISTLOSS)
    {
        ATTR_PROC_R_DISTLOSS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_R_DISTLOSS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_VRM_VOFFSET)
    {
        ATTR_PROC_VRM_VOFFSET_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_VRM_VOFFSET, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_CORE_MAX)
    {
        ATTR_FREQ_CORE_MAX_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_CORE_MAX, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MVPD_FREQ_CORE_NOMINAL)
    {
        ATTR_MVPD_FREQ_CORE_NOMINAL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MVPD_FREQ_CORE_NOMINAL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_1)
    {
        ATTR_SCRATCH_UINT8_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_2)
    {
        ATTR_SCRATCH_UINT8_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_1)
    {
        ATTR_SCRATCH_UINT32_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_2)
    {
        ATTR_SCRATCH_UINT32_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_1)
    {
        ATTR_SCRATCH_UINT64_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_2)
    {
        ATTR_SCRATCH_UINT64_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_ARRAY_1)
    {
        ATTR_SCRATCH_UINT8_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT8_ARRAY_2)
    {
        ATTR_SCRATCH_UINT8_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY_1)
    {
        ATTR_SCRATCH_UINT32_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY_2)
    {
        ATTR_SCRATCH_UINT32_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_SCRATCH_UINT64_ARRAY_1)
    {
        ATTR_SCRATCH_UINT64_ARRAY_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_ARRAY_1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT64_ARRAY_2)
    {
        ATTR_SCRATCH_UINT64_ARRAY_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_ARRAY_2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8)
    {
        ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_DUMMY_SCRATCH_PLAT_INIT_UINT8, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EXECUTION_PLATFORM)
    {
        ATTR_EXECUTION_PLATFORM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EXECUTION_PLATFORM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_IS_SIMULATION)
    {
        ATTR_IS_SIMULATION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_IS_SIMULATION, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_EPS_TABLE_TYPE)
    {
        ATTR_PROC_EPS_TABLE_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_EPS_TABLE_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FABRIC_PUMP_MODE)
    {
        ATTR_PROC_FABRIC_PUMP_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FABRIC_PUMP_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_X_BUS_WIDTH)
    {
        ATTR_PROC_X_BUS_WIDTH_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_X_BUS_WIDTH, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_ALL_MCS_IN_INTERLEAVING_GROUP)
    {
        ATTR_ALL_MCS_IN_INTERLEAVING_GROUP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_ALL_MCS_IN_INTERLEAVING_GROUP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_UNIT_POS)
    {
        ATTR_CHIP_UNIT_POS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_UNIT_POS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EI_BUS_RX_MSB_LSB_SWAP)
    {
        ATTR_EI_BUS_RX_MSB_LSB_SWAP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EI_BUS_RX_MSB_LSB_SWAP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EI_BUS_TX_MSB_LSB_SWAP)
    {
        ATTR_EI_BUS_TX_MSB_LSB_SWAP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EI_BUS_TX_MSB_LSB_SWAP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FUNCTIONAL)
    {
        ATTR_FUNCTIONAL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FUNCTIONAL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_DRAM_DEVICE_TYPE)
    {
        ATTR_SPD_DRAM_DEVICE_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_DRAM_DEVICE_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_TYPE)
    {
        ATTR_SPD_MODULE_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_BANKS)
    {
        ATTR_SPD_SDRAM_BANKS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_BANKS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_DENSITY)
    {
        ATTR_SPD_SDRAM_DENSITY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_DENSITY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_ROWS)
    {
        ATTR_SPD_SDRAM_ROWS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_ROWS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_COLUMNS)
    {
        ATTR_SPD_SDRAM_COLUMNS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_COLUMNS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_NOMINAL_VOLTAGE)
    {
        ATTR_SPD_MODULE_NOMINAL_VOLTAGE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_NOMINAL_VOLTAGE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_NUM_RANKS)
    {
        ATTR_SPD_NUM_RANKS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_NUM_RANKS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_DRAM_WIDTH)
    {
        ATTR_SPD_DRAM_WIDTH_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_DRAM_WIDTH, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_MEMORY_BUS_WIDTH)
    {
        ATTR_SPD_MODULE_MEMORY_BUS_WIDTH_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_MEMORY_BUS_WIDTH, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FTB_DIVIDEND)
    {
        ATTR_SPD_FTB_DIVIDEND_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FTB_DIVIDEND, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FTB_DIVISOR)
    {
        ATTR_SPD_FTB_DIVISOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FTB_DIVISOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MTB_DIVIDEND)
    {
        ATTR_SPD_MTB_DIVIDEND_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MTB_DIVIDEND, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MTB_DIVISOR)
    {
        ATTR_SPD_MTB_DIVISOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MTB_DIVISOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TCKMIN)
    {
        ATTR_SPD_TCKMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TCKMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_CAS_LATENCIES_SUPPORTED)
    {
        ATTR_SPD_CAS_LATENCIES_SUPPORTED_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_CAS_LATENCIES_SUPPORTED, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TAAMIN)
    {
        ATTR_SPD_TAAMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TAAMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TWRMIN)
    {
        ATTR_SPD_TWRMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TWRMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRCDMIN)
    {
        ATTR_SPD_TRCDMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRCDMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRRDMIN)
    {
        ATTR_SPD_TRRDMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRRDMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRPMIN)
    {
        ATTR_SPD_TRPMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRPMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRASMIN)
    {
        ATTR_SPD_TRASMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRASMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRCMIN)
    {
        ATTR_SPD_TRCMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRCMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRFCMIN)
    {
        ATTR_SPD_TRFCMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRFCMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TWTRMIN)
    {
        ATTR_SPD_TWTRMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TWTRMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TRTPMIN)
    {
        ATTR_SPD_TRTPMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TRTPMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_TFAWMIN)
    {
        ATTR_SPD_TFAWMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_TFAWMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_OPTIONAL_FEATURES)
    {
        ATTR_SPD_SDRAM_OPTIONAL_FEATURES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_OPTIONAL_FEATURES, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_THERMAL_AND_REFRESH_OPTIONS)
    {
        ATTR_SPD_SDRAM_THERMAL_AND_REFRESH_OPTIONS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_THERMAL_AND_REFRESH_OPTIONS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_THERMAL_SENSOR)
    {
        ATTR_SPD_MODULE_THERMAL_SENSOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_THERMAL_SENSOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_DEVICE_TYPE)
    {
        ATTR_SPD_SDRAM_DEVICE_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_DEVICE_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_DEVICE_TYPE_SIGNAL_LOADING)
    {
        ATTR_SPD_SDRAM_DEVICE_TYPE_SIGNAL_LOADING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_DEVICE_TYPE_SIGNAL_LOADING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_SDRAM_DIE_COUNT)
    {
        ATTR_SPD_SDRAM_DIE_COUNT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_SDRAM_DIE_COUNT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FINE_OFFSET_TCKMIN)
    {
        ATTR_SPD_FINE_OFFSET_TCKMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FINE_OFFSET_TCKMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FINE_OFFSET_TAAMIN)
    {
        ATTR_SPD_FINE_OFFSET_TAAMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FINE_OFFSET_TAAMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FINE_OFFSET_TRCDMIN)
    {
        ATTR_SPD_FINE_OFFSET_TRCDMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FINE_OFFSET_TRCDMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FINE_OFFSET_TRPMIN)
    {
        ATTR_SPD_FINE_OFFSET_TRPMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FINE_OFFSET_TRPMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_FINE_OFFSET_TRCMIN)
    {
        ATTR_SPD_FINE_OFFSET_TRCMIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_FINE_OFFSET_TRCMIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_NUM_OF_REGISTERS_USED_ON_RDIMM)
    {
        ATTR_SPD_NUM_OF_REGISTERS_USED_ON_RDIMM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_NUM_OF_REGISTERS_USED_ON_RDIMM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_SPECIFIC_SECTION)
    {
        ATTR_SPD_MODULE_SPECIFIC_SECTION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_SPECIFIC_SECTION, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SPD_MODULE_ID_MODULE_MANUFACTURERS_JEDEC_ID_CODE)
    {
        ATTR_SPD_MODULE_ID_MODULE_MANUFACTURERS_JEDEC_ID_CODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_ID_MODULE_MANUFACTURERS_JEDEC_ID_CODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_ID_MODULE_MANUFACTURING_LOCATION)
    {
        ATTR_SPD_MODULE_ID_MODULE_MANUFACTURING_LOCATION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_ID_MODULE_MANUFACTURING_LOCATION, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_ID_MODULE_MANUFACTURING_DATE)
    {
        ATTR_SPD_MODULE_ID_MODULE_MANUFACTURING_DATE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_ID_MODULE_MANUFACTURING_DATE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_ID_MODULE_SERIAL_NUMBER)
    {
        ATTR_SPD_MODULE_ID_MODULE_SERIAL_NUMBER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_ID_MODULE_SERIAL_NUMBER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_CYCLICAL_REDUNDANCY_CODE)
    {
        ATTR_SPD_CYCLICAL_REDUNDANCY_CODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_CYCLICAL_REDUNDANCY_CODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_MODULE_PART_NUMBER)
    {
        ATTR_SPD_MODULE_PART_NUMBER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_PART_NUMBER, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SPD_MODULE_REVISION_CODE)
    {
        ATTR_SPD_MODULE_REVISION_CODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_MODULE_REVISION_CODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_DRAM_MANUFACTURER_JEDEC_ID_CODE)
    {
        ATTR_SPD_DRAM_MANUFACTURER_JEDEC_ID_CODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_DRAM_MANUFACTURER_JEDEC_ID_CODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SPD_BAD_DQ_DATA)
    {
        ATTR_SPD_BAD_DQ_DATA_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SPD_BAD_DQ_DATA, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_VOLT)
    {
        ATTR_MSS_VOLT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_VOLT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_FREQ)
    {
        ATTR_MSS_FREQ_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_FREQ, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_DIMM_MFG_ID_CODE)
    {
        ATTR_MSS_DIMM_MFG_ID_CODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_DIMM_MFG_ID_CODE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_RANKS_CONFIGED)
    {
        ATTR_EFF_DIMM_RANKS_CONFIGED_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_RANKS_CONFIGED, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_NUM_RANKS_PER_DIMM)
    {
        ATTR_EFF_NUM_RANKS_PER_DIMM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_NUM_RANKS_PER_DIMM, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_TYPE)
    {
        ATTR_EFF_DIMM_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_TYPE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_WIDTH)
    {
        ATTR_EFF_DRAM_WIDTH_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WIDTH, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_GEN)
    {
        ATTR_EFF_DRAM_GEN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_GEN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_PRIMARY_RANK_GROUP0)
    {
        ATTR_EFF_PRIMARY_RANK_GROUP0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_PRIMARY_RANK_GROUP0, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_PRIMARY_RANK_GROUP1)
    {
        ATTR_EFF_PRIMARY_RANK_GROUP1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_PRIMARY_RANK_GROUP1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_PRIMARY_RANK_GROUP2)
    {
        ATTR_EFF_PRIMARY_RANK_GROUP2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_PRIMARY_RANK_GROUP2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_PRIMARY_RANK_GROUP3)
    {
        ATTR_EFF_PRIMARY_RANK_GROUP3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_PRIMARY_RANK_GROUP3, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_SECONDARY_RANK_GROUP0)
    {
        ATTR_EFF_SECONDARY_RANK_GROUP0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SECONDARY_RANK_GROUP0, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_SECONDARY_RANK_GROUP1)
    {
        ATTR_EFF_SECONDARY_RANK_GROUP1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SECONDARY_RANK_GROUP1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_SECONDARY_RANK_GROUP2)
    {
        ATTR_EFF_SECONDARY_RANK_GROUP2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SECONDARY_RANK_GROUP2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_SECONDARY_RANK_GROUP3)
    {
        ATTR_EFF_SECONDARY_RANK_GROUP3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SECONDARY_RANK_GROUP3, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_TERTIARY_RANK_GROUP0)
    {
        ATTR_EFF_TERTIARY_RANK_GROUP0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_TERTIARY_RANK_GROUP0, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_TERTIARY_RANK_GROUP1)
    {
        ATTR_EFF_TERTIARY_RANK_GROUP1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_TERTIARY_RANK_GROUP1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_TERTIARY_RANK_GROUP2)
    {
        ATTR_EFF_TERTIARY_RANK_GROUP2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_TERTIARY_RANK_GROUP2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_TERTIARY_RANK_GROUP3)
    {
        ATTR_EFF_TERTIARY_RANK_GROUP3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_TERTIARY_RANK_GROUP3, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_QUATERNARY_RANK_GROUP0)
    {
        ATTR_EFF_QUATERNARY_RANK_GROUP0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_QUATERNARY_RANK_GROUP0, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_QUATERNARY_RANK_GROUP1)
    {
        ATTR_EFF_QUATERNARY_RANK_GROUP1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_QUATERNARY_RANK_GROUP1, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_QUATERNARY_RANK_GROUP2)
    {
        ATTR_EFF_QUATERNARY_RANK_GROUP2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_QUATERNARY_RANK_GROUP2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_QUATERNARY_RANK_GROUP3)
    {
        ATTR_EFF_QUATERNARY_RANK_GROUP3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_QUATERNARY_RANK_GROUP3, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_EFF_ODT_RD)
    {
        ATTR_EFF_ODT_RD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_ODT_RD, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_ODT_WR)
    {
        ATTR_EFF_ODT_WR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_ODT_WR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_CKE_MAP)
    {
        ATTR_EFF_CKE_MAP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CKE_MAP, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DIMM_SPARE)
    {
        ATTR_EFF_DIMM_SPARE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_SPARE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DRAM_RON)
    {
        ATTR_EFF_DRAM_RON_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RON, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_RTT_NOM)
    {
        ATTR_EFF_DRAM_RTT_NOM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RTT_NOM, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DRAM_RTT_WR)
    {
        ATTR_EFF_DRAM_RTT_WR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RTT_WR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2][i_arrayIndex3];
    }
    else if (i_id == ATTR_EFF_DRAM_WR_VREF)
    {
        ATTR_EFF_DRAM_WR_VREF_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR_VREF, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_WR_VREF_SCHMOO)
    {
        ATTR_EFF_DRAM_WR_VREF_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR_VREF_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_DQ_DQS)
    {
        ATTR_EFF_CEN_DRV_IMP_DQ_DQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_DQ_DQS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_CMD)
    {
        ATTR_EFF_CEN_DRV_IMP_CMD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_CMD, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_CNTL)
    {
        ATTR_EFF_CEN_DRV_IMP_CNTL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_CNTL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_DQ_DQS_SCHMOO)
    {
        ATTR_EFF_CEN_DRV_IMP_DQ_DQS_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_DQ_DQS_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_CMD_SCHMOO)
    {
        ATTR_EFF_CEN_DRV_IMP_CMD_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_CMD_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_DRV_IMP_CNTL_SCHMOO)
    {
        ATTR_EFF_CEN_DRV_IMP_CNTL_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_DRV_IMP_CNTL_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_RCV_IMP_DQ_DQS)
    {
        ATTR_EFF_CEN_RCV_IMP_DQ_DQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RCV_IMP_DQ_DQS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_RCV_IMP_DQ_DQS_SCHMOO)
    {
        ATTR_EFF_CEN_RCV_IMP_DQ_DQS_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RCV_IMP_DQ_DQS_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_RCV_IMP_CMD_SCHMOO)
    {
        ATTR_EFF_CEN_RCV_IMP_CMD_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RCV_IMP_CMD_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_RCV_IMP_CNTL_SCHMOO)
    {
        ATTR_EFF_CEN_RCV_IMP_CNTL_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RCV_IMP_CNTL_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_DQ_DQS)
    {
        ATTR_EFF_CEN_SLEW_RATE_DQ_DQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_DQ_DQS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_CMD)
    {
        ATTR_EFF_CEN_SLEW_RATE_CMD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_CMD, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_CNTL)
    {
        ATTR_EFF_CEN_SLEW_RATE_CNTL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_CNTL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_DQ_DQS_SCHMOO)
    {
        ATTR_EFF_CEN_SLEW_RATE_DQ_DQS_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_DQ_DQS_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_CMD_SCHMOO)
    {
        ATTR_EFF_CEN_SLEW_RATE_CMD_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_CMD_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_SLEW_RATE_CNTL_SCHMOO)
    {
        ATTR_EFF_CEN_SLEW_RATE_CNTL_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_SLEW_RATE_CNTL_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_RD_VREF)
    {
        ATTR_EFF_CEN_RD_VREF_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RD_VREF, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_CEN_RD_VREF_SCHMOO)
    {
        ATTR_EFF_CEN_RD_VREF_SCHMOO_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_CEN_RD_VREF_SCHMOO, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DIMM_SIZE)
    {
        ATTR_EFF_DIMM_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_SIZE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DRAM_BANKS)
    {
        ATTR_EFF_DRAM_BANKS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_BANKS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_ROWS)
    {
        ATTR_EFF_DRAM_ROWS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_ROWS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_COLS)
    {
        ATTR_EFF_DRAM_COLS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_COLS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_DENSITY)
    {
        ATTR_EFF_DRAM_DENSITY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DENSITY, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRCD)
    {
        ATTR_EFF_DRAM_TRCD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRCD, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRRD)
    {
        ATTR_EFF_DRAM_TRRD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRRD, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRP)
    {
        ATTR_EFF_DRAM_TRP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRAS)
    {
        ATTR_EFF_DRAM_TRAS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRAS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRC)
    {
        ATTR_EFF_DRAM_TRC_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRC, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRFI)
    {
        ATTR_EFF_DRAM_TRFI_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRFI, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRFC)
    {
        ATTR_EFF_DRAM_TRFC_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRFC, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TWTR)
    {
        ATTR_EFF_DRAM_TWTR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TWTR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TRTP)
    {
        ATTR_EFF_DRAM_TRTP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TRTP, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TFAW)
    {
        ATTR_EFF_DRAM_TFAW_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TFAW, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_BL)
    {
        ATTR_EFF_DRAM_BL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_BL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_CL)
    {
        ATTR_EFF_DRAM_CL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_CL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_AL)
    {
        ATTR_EFF_DRAM_AL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_AL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_CWL)
    {
        ATTR_EFF_DRAM_CWL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_CWL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_RBT)
    {
        ATTR_EFF_DRAM_RBT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_RBT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TM)
    {
        ATTR_EFF_DRAM_TM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TM, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_DLL_RESET)
    {
        ATTR_EFF_DRAM_DLL_RESET_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DLL_RESET, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_WR)
    {
        ATTR_EFF_DRAM_WR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_DLL_PPD)
    {
        ATTR_EFF_DRAM_DLL_PPD_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DLL_PPD, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_DLL_ENABLE)
    {
        ATTR_EFF_DRAM_DLL_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_DLL_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_TDQS)
    {
        ATTR_EFF_DRAM_TDQS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_TDQS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_WR_LVL_ENABLE)
    {
        ATTR_EFF_DRAM_WR_LVL_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_WR_LVL_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_OUTPUT_BUFFER)
    {
        ATTR_EFF_DRAM_OUTPUT_BUFFER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_OUTPUT_BUFFER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_PASR)
    {
        ATTR_EFF_DRAM_PASR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_PASR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_ASR)
    {
        ATTR_EFF_DRAM_ASR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_ASR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DRAM_SRT)
    {
        ATTR_EFF_DRAM_SRT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DRAM_SRT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_MPR_LOC)
    {
        ATTR_EFF_MPR_LOC_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_MPR_LOC, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_MPR_MODE)
    {
        ATTR_EFF_MPR_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_MPR_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15)
    {
        ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_RCD_IBT)
    {
        ATTR_EFF_DIMM_RCD_IBT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_RCD_IBT, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_DIMM_RCD_MIRROR_MODE)
    {
        ATTR_EFF_DIMM_RCD_MIRROR_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_DIMM_RCD_MIRROR_MODE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_SCHMOO_MODE)
    {
        ATTR_EFF_SCHMOO_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_ADDR_MODE)
    {
        ATTR_EFF_SCHMOO_ADDR_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_ADDR_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_TEST_VALID)
    {
        ATTR_EFF_SCHMOO_TEST_VALID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_TEST_VALID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_PARAM_VALID)
    {
        ATTR_EFF_SCHMOO_PARAM_VALID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_PARAM_VALID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_WR_EYE_MIN_MARGIN)
    {
        ATTR_EFF_SCHMOO_WR_EYE_MIN_MARGIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_WR_EYE_MIN_MARGIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_RD_EYE_MIN_MARGIN)
    {
        ATTR_EFF_SCHMOO_RD_EYE_MIN_MARGIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_RD_EYE_MIN_MARGIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_DQS_CLK_MIN_MARGIN)
    {
        ATTR_EFF_SCHMOO_DQS_CLK_MIN_MARGIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_DQS_CLK_MIN_MARGIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_RD_GATE_MIN_MARGIN)
    {
        ATTR_EFF_SCHMOO_RD_GATE_MIN_MARGIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_RD_GATE_MIN_MARGIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_SCHMOO_ADDR_CMD_MIN_MARGIN)
    {
        ATTR_EFF_SCHMOO_ADDR_CMD_MIN_MARGIN_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_SCHMOO_ADDR_CMD_MIN_MARGIN, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_MEMCAL_INTERVAL)
    {
        ATTR_EFF_MEMCAL_INTERVAL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_MEMCAL_INTERVAL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_ZQCAL_INTERVAL)
    {
        ATTR_EFF_ZQCAL_INTERVAL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_ZQCAL_INTERVAL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_IBM_TYPE)
    {
        ATTR_EFF_IBM_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_IBM_TYPE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_NUM_DROPS_PER_PORT)
    {
        ATTR_EFF_NUM_DROPS_PER_PORT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_NUM_DROPS_PER_PORT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_EFF_STACK_TYPE)
    {
        ATTR_EFF_STACK_TYPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_STACK_TYPE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_NUM_MASTER_RANKS_PER_DIMM)
    {
        ATTR_EFF_NUM_MASTER_RANKS_PER_DIMM_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_NUM_MASTER_RANKS_PER_DIMM, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_NUM_PACKAGES_PER_RANK)
    {
        ATTR_EFF_NUM_PACKAGES_PER_RANK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_NUM_PACKAGES_PER_RANK, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_NUM_DIES_PER_PACKAGE)
    {
        ATTR_EFF_NUM_DIES_PER_PACKAGE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_NUM_DIES_PER_PACKAGE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_EFF_RDIMM_NUM_REGISTERS)
    {
        ATTR_EFF_RDIMM_NUM_REGISTERS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_EFF_RDIMM_NUM_REGISTERS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_THROTTLE_NUMERATOR)
    {
        ATTR_MSS_THROTTLE_NUMERATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_THROTTLE_NUMERATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_THROTTLE_DENOMINATOR)
    {
        ATTR_MSS_THROTTLE_DENOMINATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_THROTTLE_DENOMINATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_THROTTLE_CHANNEL_NUMERATOR)
    {
        ATTR_MSS_THROTTLE_CHANNEL_NUMERATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_THROTTLE_CHANNEL_NUMERATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_THROTTLE_CHANNEL_DENOMINATOR)
    {
        ATTR_MSS_THROTTLE_CHANNEL_DENOMINATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_THROTTLE_CHANNEL_DENOMINATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_WATT_TARGET)
    {
        ATTR_MSS_WATT_TARGET_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_WATT_TARGET, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_POWER_SLOPE)
    {
        ATTR_MSS_POWER_SLOPE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_POWER_SLOPE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_POWER_SLOPE2)
    {
        ATTR_MSS_POWER_SLOPE2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_POWER_SLOPE2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_POWER_INT)
    {
        ATTR_MSS_POWER_INT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_POWER_INT, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_POWER_INT2)
    {
        ATTR_MSS_POWER_INT2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_POWER_INT2, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_DIMM_MAXBANDWIDTH_GBS)
    {
        ATTR_MSS_DIMM_MAXBANDWIDTH_GBS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_DIMM_MAXBANDWIDTH_GBS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_DIMM_MAXBANDWIDTH_MRS)
    {
        ATTR_MSS_DIMM_MAXBANDWIDTH_MRS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_DIMM_MAXBANDWIDTH_MRS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_CHANNEL_MAXBANDWIDTH_GBS)
    {
        ATTR_MSS_CHANNEL_MAXBANDWIDTH_GBS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_CHANNEL_MAXBANDWIDTH_GBS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_CHANNEL_MAXBANDWIDTH_MRS)
    {
        ATTR_MSS_CHANNEL_MAXBANDWIDTH_MRS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_CHANNEL_MAXBANDWIDTH_MRS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_DIMM_MAXPOWER)
    {
        ATTR_MSS_DIMM_MAXPOWER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_DIMM_MAXPOWER, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_CHANNEL_MAXPOWER)
    {
        ATTR_MSS_CHANNEL_MAXPOWER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_CHANNEL_MAXPOWER, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_RUNTIME_MEM_THROTTLE_DIMM_NUMERATOR)
    {
        ATTR_MSS_RUNTIME_MEM_THROTTLE_DIMM_NUMERATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_RUNTIME_MEM_THROTTLE_DIMM_NUMERATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_RUNTIME_MEM_THROTTLE_DIMM_DENOMINATOR)
    {
        ATTR_MSS_RUNTIME_MEM_THROTTLE_DIMM_DENOMINATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_RUNTIME_MEM_THROTTLE_DIMM_DENOMINATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_RUNTIME_MEM_THROTTLE_CHANNEL_NUMERATOR)
    {
        ATTR_MSS_RUNTIME_MEM_THROTTLE_CHANNEL_NUMERATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_RUNTIME_MEM_THROTTLE_CHANNEL_NUMERATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_RUNTIME_MEM_THROTTLE_CHANNEL_DENOMINATOR)
    {
        ATTR_MSS_RUNTIME_MEM_THROTTLE_CHANNEL_DENOMINATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_RUNTIME_MEM_THROTTLE_CHANNEL_DENOMINATOR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MRW_SAFEMODE_MEM_THROTTLE_DIMM_NUMERATOR)
    {
        ATTR_MRW_SAFEMODE_MEM_THROTTLE_DIMM_NUMERATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MRW_SAFEMODE_MEM_THROTTLE_DIMM_NUMERATOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MRW_SAFEMODE_MEM_THROTTLE_DIMM_DENOMINATOR)
    {
        ATTR_MRW_SAFEMODE_MEM_THROTTLE_DIMM_DENOMINATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MRW_SAFEMODE_MEM_THROTTLE_DIMM_DENOMINATOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MRW_SAFEMODE_MEM_THROTTLE_CHANNEL_NUMERATOR)
    {
        ATTR_MRW_SAFEMODE_MEM_THROTTLE_CHANNEL_NUMERATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MRW_SAFEMODE_MEM_THROTTLE_CHANNEL_NUMERATOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MRW_SAFEMODE_MEM_THROTTLE_CHANNEL_DENOMINATOR)
    {
        ATTR_MRW_SAFEMODE_MEM_THROTTLE_CHANNEL_DENOMINATOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MRW_SAFEMODE_MEM_THROTTLE_CHANNEL_DENOMINATOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MRW_THERMAL_MEMORY_POWER_LIMIT)
    {
        ATTR_MRW_THERMAL_MEMORY_POWER_LIMIT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MRW_THERMAL_MEMORY_POWER_LIMIT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_INTERLEAVE_ENABLE)
    {
        ATTR_MSS_INTERLEAVE_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_INTERLEAVE_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_MCA_HASH_MODE)
    {
        ATTR_MSS_MCA_HASH_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_MCA_HASH_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_MBA_ADDR_INTERLEAVE_BIT)
    {
        ATTR_MSS_MBA_ADDR_INTERLEAVE_BIT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_MBA_ADDR_INTERLEAVE_BIT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_MBA_CACHELINE_INTERLEAVE_MODE)
    {
        ATTR_MSS_MBA_CACHELINE_INTERLEAVE_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_MBA_CACHELINE_INTERLEAVE_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_CACHE_ENABLE)
    {
        ATTR_MSS_CACHE_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_CACHE_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_PREFETCH_ENABLE)
    {
        ATTR_MSS_PREFETCH_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_PREFETCH_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_CLEANER_ENABLE)
    {
        ATTR_MSS_CLEANER_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_CLEANER_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_LAB_OVERRIDE_FOR_MEM_PLL)
    {
        ATTR_MSS_LAB_OVERRIDE_FOR_MEM_PLL_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_LAB_OVERRIDE_FOR_MEM_PLL, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_MEM_MC_IN_GROUP)
    {
        ATTR_MSS_MEM_MC_IN_GROUP_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_MEM_MC_IN_GROUP, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_MSS_MCS_GROUP_32)
    {
        ATTR_MSS_MCS_GROUP_32_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_MCS_GROUP_32, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_EFF_DIMM_FUNCTIONAL_VECTOR)
    {
        ATTR_MSS_EFF_DIMM_FUNCTIONAL_VECTOR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_EFF_DIMM_FUNCTIONAL_VECTOR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_CAL_STEP_ENABLE)
    {
        ATTR_MSS_CAL_STEP_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_CAL_STEP_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_MEM_IPL_COMPLETE)
    {
        ATTR_MSS_MEM_IPL_COMPLETE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_MEM_IPL_COMPLETE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_SLEW_RATE_DATA)
    {
        ATTR_MSS_SLEW_RATE_DATA_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_SLEW_RATE_DATA, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_SLEW_RATE_ADR)
    {
        ATTR_MSS_SLEW_RATE_ADR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_SLEW_RATE_ADR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_MSS_ECID0)
    {
        ATTR_MSS_ECID0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_ECID0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MSS_ECID1)
    {
        ATTR_MSS_ECID1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MSS_ECID1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CENTAUR_EC_WRITE_FIR_MASK_FEATURE)
    {
        ATTR_CENTAUR_EC_WRITE_FIR_MASK_FEATURE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CENTAUR_EC_WRITE_FIR_MASK_FEATURE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FREQ_CORE)
    {
        ATTR_FREQ_CORE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FREQ_CORE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_EPS_GB_PERCENTAGE)
    {
        ATTR_PROC_EPS_GB_PERCENTAGE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_EPS_GB_PERCENTAGE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_EPS_GB_DIRECTION)
    {
        ATTR_PROC_EPS_GB_DIRECTION_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_EPS_GB_DIRECTION, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FABRIC_ASYNC_SAFE_MODE)
    {
        ATTR_PROC_FABRIC_ASYNC_SAFE_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FABRIC_ASYNC_SAFE_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_PCIE_NOT_F_LINK)
    {
        ATTR_PROC_PCIE_NOT_F_LINK_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_PCIE_NOT_F_LINK, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_L3_BAR1_REG)
    {
        ATTR_PROC_L3_BAR1_REG_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_L3_BAR1_REG, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_L3_BAR2_REG)
    {
        ATTR_PROC_L3_BAR2_REG_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_L3_BAR2_REG, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_L3_BAR_GROUP_MASK_REG)
    {
        ATTR_PROC_L3_BAR_GROUP_MASK_REG_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_L3_BAR_GROUP_MASK_REG, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_MEM_BASE)
    {
        ATTR_PROC_MEM_BASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_MEM_BASE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_MEM_BASES)
    {
        ATTR_PROC_MEM_BASES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_MEM_BASES, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_MEM_SIZES)
    {
        ATTR_PROC_MEM_SIZES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_MEM_SIZES, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_MIRROR_BASE)
    {
        ATTR_PROC_MIRROR_BASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_MIRROR_BASE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_MIRROR_BASES)
    {
        ATTR_PROC_MIRROR_BASES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_MIRROR_BASES, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_MIRROR_SIZES)
    {
        ATTR_PROC_MIRROR_SIZES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_MIRROR_SIZES, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_FOREIGN_NEAR_BASE)
    {
        ATTR_PROC_FOREIGN_NEAR_BASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FOREIGN_NEAR_BASE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_FOREIGN_NEAR_SIZE)
    {
        ATTR_PROC_FOREIGN_NEAR_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FOREIGN_NEAR_SIZE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_FOREIGN_FAR_BASE)
    {
        ATTR_PROC_FOREIGN_FAR_BASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FOREIGN_FAR_BASE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_FOREIGN_FAR_SIZE)
    {
        ATTR_PROC_FOREIGN_FAR_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FOREIGN_FAR_SIZE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_HA_BASE)
    {
        ATTR_PROC_HA_BASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_HA_BASE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_HA_SIZE)
    {
        ATTR_PROC_HA_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_HA_SIZE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PROC_PSI_BRIDGE_BAR_ENABLE)
    {
        ATTR_PROC_PSI_BRIDGE_BAR_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_PSI_BRIDGE_BAR_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_PSI_BRIDGE_BAR_BASE_ADDR)
    {
        ATTR_PROC_PSI_BRIDGE_BAR_BASE_ADDR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_PSI_BRIDGE_BAR_BASE_ADDR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FSP_BAR_ENABLE)
    {
        ATTR_PROC_FSP_BAR_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FSP_BAR_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FSP_BAR_BASE_ADDR)
    {
        ATTR_PROC_FSP_BAR_BASE_ADDR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FSP_BAR_BASE_ADDR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FSP_BAR_SIZE)
    {
        ATTR_PROC_FSP_BAR_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FSP_BAR_SIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_FSP_MMIO_MASK_SIZE)
    {
        ATTR_PROC_FSP_MMIO_MASK_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_FSP_MMIO_MASK_SIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_INTP_BAR_ENABLE)
    {
        ATTR_PROC_INTP_BAR_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_INTP_BAR_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_INTP_BAR_BASE_ADDR)
    {
        ATTR_PROC_INTP_BAR_BASE_ADDR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_INTP_BAR_BASE_ADDR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_NX_MMIO_BAR_ENABLE)
    {
        ATTR_PROC_NX_MMIO_BAR_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_NX_MMIO_BAR_ENABLE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_NX_MMIO_BAR_BASE_ADDR)
    {
        ATTR_PROC_NX_MMIO_BAR_BASE_ADDR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_NX_MMIO_BAR_BASE_ADDR, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_NX_MMIO_BAR_SIZE)
    {
        ATTR_PROC_NX_MMIO_BAR_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_NX_MMIO_BAR_SIZE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_PCIE_BAR_ENABLE)
    {
        ATTR_PROC_PCIE_BAR_ENABLE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_PCIE_BAR_ENABLE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_PROC_PCIE_BAR_BASE_ADDR)
    {
        ATTR_PROC_PCIE_BAR_BASE_ADDR_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_PCIE_BAR_BASE_ADDR, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_PROC_PCIE_BAR_SIZE)
    {
        ATTR_PROC_PCIE_BAR_SIZE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_PCIE_BAR_SIZE, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1][i_arrayIndex2];
    }
    else if (i_id == ATTR_SBE_SEEPROM_I2C_ADDRESS_BYTES)
    {
        ATTR_SBE_SEEPROM_I2C_ADDRESS_BYTES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SBE_SEEPROM_I2C_ADDRESS_BYTES, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SBE_SEEPROM_I2C_DEVICE_ADDRESS)
    {
        ATTR_SBE_SEEPROM_I2C_DEVICE_ADDRESS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SBE_SEEPROM_I2C_DEVICE_ADDRESS, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SBE_SEEPROM_I2C_PORT)
    {
        ATTR_SBE_SEEPROM_I2C_PORT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SBE_SEEPROM_I2C_PORT, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_PNOR_I2C_ADDRESS_BYTES)
    {
        ATTR_PNOR_I2C_ADDRESS_BYTES_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PNOR_I2C_ADDRESS_BYTES, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_SELECT_CLOCK_MUX_MODE)
    {
        ATTR_PROC_SELECT_CLOCK_MUX_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_SELECT_CLOCK_MUX_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PROC_SELECT_BOOT_MASTER)
    {
        ATTR_PROC_SELECT_BOOT_MASTER_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PROC_SELECT_BOOT_MASTER, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else
    {
        FAPI_ERR("fapiGetInitFileAttr: Unrecognized attr: %d", i_id);
        l_rc.setFapiError(FAPI_RC_INVALID_ATTR_GET);
        ReturnCodeFfdc::addEIFfdc(l_rc, static_cast<uint32_t>(i_id));
    }

    if (l_rc)
    {
        FAPI_ERR("fapiGetInitFileAttr: Error getting attr");
    }

    return l_rc;
}

}
