# $Header$
# Makefile for the ecmd Extensions

EXTENSION_NAME   := fapi2

# Base info and default build rules
SUBDIR     := ext/${EXTENSION_NAME}/cmd/
include ../../../makefile.rules

# This is Additional extension for the client api
SOURCE       := fapi2MiscUser.C

# These are additional includes for the client api
INCLUDES     :=

# Include the common extension makefile to do all the work
include ../../template/cmd/makefile.cmd

