#ifndef cmdStructs_h
#define cmdStructs_h


/**
 * @file cmdStructs.H
 * @brief eCMD Command line Extension Structures

 * Extension Owner : Matt Light
*/

//--------------------------------------------------------------------
// Includes
//--------------------------------------------------------------------


//--------------------------------------------------------------------
//  Forward References                                                
//--------------------------------------------------------------------


#define ECMD_CMD_CAPI_VERSION "1.1"          ///< eCMD CMD Extension version


#endif /* cmdStructs_h */
