#ifndef ecmdPluginExtensionSupport_h
#define ecmdPluginExtensionSupport_h
/* $Header$ */
// Copyright **********************************************************
//                                                                      
// File ecmdPluginExtensionSupport.H                                               
//                                                                      
// IBM Confidential                                                     
// OCO Source Materials                                                 
// 9400 Licensed Internal Code                                          
// (C) COPYRIGHT IBM CORP. 1996                                         
//                                                                      
// The source code for this program is not published or otherwise       
// divested of its trade secrets, irrespective of what has been         
// deposited with the U.S. Copyright Office.                             
//                                                                      
// End Copyright ******************************************************

//--------------------------------------------------------------------
// Includes
//--------------------------------------------------------------------


//--------------------------------------------------------------------
//  Forward References                                                
//--------------------------------------------------------------------

/* These defines what extensions are supported by this plugin */
/* Enable or disable these defines as needed by your plugin */
/* The eCMD makefiles take care of turning on the appropriate defines for the extentions being built in CVS */


/* The Cronus/IP GFW Extension */
//#define ECMD_CIP_EXTENSION_SUPPORT

/* The Cronus Extension */
//#define ECMD_CRO_EXTENSION_SUPPORT

/* The Eclipz IP/Cronus Extension */
//#define ECMD_EIP_EXTENSION_SUPPORT

/* The Apollo IP/Cronus Extension */
//#define ECMD_AIP_EXTENSION_SUPPORT

/* The GFW IP Extension */
//#define ECMD_GIP_EXTENSION_SUPPORT

/* The Z Series Extension */
//#define ECMD_ZSE_EXTENSION_SUPPORT

/* The BML Extension */
//#define ECMD_BML_EXTENSION_SUPPORT

/* The Mambo Extension */
//#define ECMD_MBO_EXTENSION_SUPPORT

/* The CommandLine Extension */
//#define ECMD_CMD_EXTENSION_SUPPORT

#endif /* ecmdPluginExtensionSupport_h */

// Change Log *********************************************************
//                                                                      
//  Flag Reason   Vers Date     Coder  Description                       
//  ---- -------- ---- -------- -----  -------------------------------   
//                              cengel Initial Creation
//
// End Change Log *****************************************************
