//IBM_PROLOG_BEGIN_TAG
//IBM_PROLOG_END_TAG

#ifndef ecmdPluginExtensionSupport_h
#define ecmdPluginExtensionSupport_h

//--------------------------------------------------------------------
// Includes
//--------------------------------------------------------------------


//--------------------------------------------------------------------
//  Forward References                                                
//--------------------------------------------------------------------

/* These defines what extensions are supported by this plugin */
/* Enable or disable these defines as needed by your plugin */
/* The eCMD makefiles take care of turning on the appropriate defines for the extentions being built in CVS */


/* The Cronus/IP GFW Extension */
//#define ECMD_CIP_EXTENSION_SUPPORT

/* The Cronus Extension */
//#define ECMD_CRO_EXTENSION_SUPPORT

/* The Eclipz IP/Cronus Extension */
//#define ECMD_EIP_EXTENSION_SUPPORT

/* The Apollo IP/Cronus Extension */
//#define ECMD_AIP_EXTENSION_SUPPORT

/* The GFW IP Extension */
//#define ECMD_GIP_EXTENSION_SUPPORT

/* The Z Series Extension */
//#define ECMD_ZSE_EXTENSION_SUPPORT

/* The BML Extension */
//#define ECMD_BML_EXTENSION_SUPPORT

/* The Mambo Extension */
//#define ECMD_MBO_EXTENSION_SUPPORT

/* The CommandLine Extension */
//#define ECMD_CMD_EXTENSION_SUPPORT

/* The FAPI (Hardware Procedure Framework) Extension */
//#define ECMD_FAPI_EXTENSION_SUPPORT

/* The FAPI2 (Hardware Procedure Framework) Extension */
//#define ECMD_FAPI2_EXTENSION_SUPPORT



#endif /* ecmdPluginExtensionSupport_h */
