# Makefile for the ecmd Capi
# Written by Chris Engel

# $Header$




# *****************************************************************************
# The Main Targets
# *****************************************************************************
all: dir 
	@echo "Exporting eCMD Dll Api Lib to export/ ..."
	@cp *.C *.H export/

clean:
	rm -rf export/

dir:
	@mkdir -p export


